apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ihv4guvqw-nodejs
  janus-idp.io/tekton: ihv4guvqw-nodejs
  backstage.io/kubernetes-id: ihv4guvqw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ihv4guvqw-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
