apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ihv4guvqw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ihv4guvqw-nodejs 
  name: ihv4guvqw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ihv4guvqw-nodejs 
