apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ihv4guvqw-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:1ac7328e8477f7b934b61205037b3b73a5698ad0@sha256:7938b30d67f044e2c05430ef671a7a2727ff9bc1f5ded986c9742634cd9be9a6
          name: container-image
